paths:
  raw: raw
  clips: clips
whisper_size: base        # tiny / base / small / medium
highlights: 1             # nº de cortes por episódio
tags: ["podcast", "cortes", "clipverso", "clipverso-ofc"]
test_mode: false          # true = pula upload para YouTube (mantenha true para testes)

openai_models:
  highlighter: o3
  editor: o3
  thumbnail: dall-e-3    # Modelo para geração de imagens
