paths:
  raw: raw
  clips: clips
whisper_size: base        # tiny / base / small / medium
highlights: 6             # nº de cortes por episódio
tags: ["cortes", "viral", "fy", "clipverso-ofc"]
test_mode: false          # true = pula upload para YouTube (mantenha true para testes)

openai_models:
  highlighter: o3
  editor: o3
  thumbnail: dall-e-3    # Modelo para geração de imagens

# Configurações de otimização de vídeo
video_optimization:
  use_gpu: true          # true = usa GPU AMD se disponível
  quality: balanced       # fast, balanced, high
  enable_parallel: true   # true = processamento paralelo quando possível

# Configurações de outros
append_outro: true        # true = anexa outro ao final de cada corte

# Configurações de upload
upload_delay:
  min_seconds: 1800       # Delay mínimo entre uploads (30 minutos)
  max_seconds: 3600       # Delay máximo entre uploads (1 hora)
